name: "🐛 Bug report"
description: Report a bug to help us improve the module.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT!**
        Before reporting a bug, please make sure that you have read through our documentation and you think your problem is indeed an issue related to our module.
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: You can use `npx nuxi info` to fill this section
      placeholder: |
        - Operating System: `Darwin`
        - Node Version:     `v18.16.0`
        - Nuxt Version:     `3.7.3`
        - CLI Version:      `3.8.4`
        - Nitro Version:    `2.6.3`
        - Package Manager:  `pnpm@8.7.4`
        - Builder:          `-`
        - User Config:      `-`
        - Runtime Modules:  `-`
        - Build Modules:    `-`
    validations:
      required: true
  - type: dropdown
    id: options
    attributes:
      label: Does the bug happen with default `security` options?
      options:
        - My bug happens even if the `security` object is not set
        - My bug happens when I set a specific option in the `security` object
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Nuxt Security Version
      placeholder: v2.1.5
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a reproduction link. A minimal [reproduction is required](https://antfu.me/posts/why-reproductions-are-required) unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "needs reproduction" label. If no reproduction is provided we might close it.
      placeholder: |
        - Either a GitHub repository that can reproduce the bug
        - Or a link to a Stackblitz playground
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description.
      placeholder: |
        - What happens ?
        - What is expected to happen ?
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context or screenshots here.
      placeholder: |
        Ideally we need
        - your full nuxt.config.ts
        - screenshots of your DevTools console
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: shell-script
